# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

if os.path.isfile("test_env.py"):
    import test_env


class TestAdminFunctionality():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_admin_login(self):
        admin_email = os.environ.get("ADMIN_EMAIL")
        admin_password = os.environ.get("ADMIN_PASSWORD")
        # self.driver.get("https://eau-royal.herokuapp.com/")
        self.driver.get("http://192.168.1.18:8000/")
        self.driver.set_window_size(1920, 1080)
        self.driver.find_element(By.ID, "user-account-button").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_login").send_keys(admin_email)
        self.driver.find_element(
            By.ID, "id_password").send_keys(admin_password)
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'submit\'])[3]").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
        time.sleep(3)

    def test_add_product(self):
        self.test_admin_login()
        self.driver.find_element(By.ID, "user-account-button").click()
        self.driver.find_element(By.LINK_TEXT, "Product Management").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_name").click()
        self.driver.find_element(By.ID, "id_name").send_keys("new product")
        self.driver.find_element(By.ID, "id_brand").click()
        dropdown = self.driver.find_element(By.ID, "id_brand")
        dropdown.find_element(By.XPATH, "//option[. = 'Dkny']").click()
        self.driver.find_element(By.ID, "id_sku").click()
        self.driver.find_element(By.ID, "id_sku").send_keys("ER789101112")
        self.driver.find_element(By.ID, "id_category").click()
        dropdown = self.driver.find_element(By.ID, "id_category")
        dropdown.find_element(By.XPATH, "//option[. = 'perfumes']").click()
        self.driver.find_element(By.ID, "id_gender").click()
        dropdown = self.driver.find_element(By.ID, "id_gender")
        dropdown.find_element(By.XPATH, "//option[. = 'all']").click()
        self.driver.find_element(By.ID, "id_has_sizes").click()
        dropdown = self.driver.find_element(By.ID, "id_has_sizes")
        dropdown.find_element(By.XPATH, "//option[. = 'Yes']").click()
        target = self.driver.find_element_by_id('id_has_sizes')
        target.location_once_scrolled_into_view
        time.sleep(2)
        self.driver.find_element(By.ID, "id_rating").click()
        self.driver.find_element(By.ID, "id_rating").send_keys("5")
        self.driver.find_element(By.ID, "id_price").click()
        self.driver.find_element(By.ID, "id_price").send_keys("45")
        self.driver.find_element(By.ID, "id_scent").click()
        self.driver.find_element(By.ID, "id_scent").send_keys("Vanilla")
        self.driver.find_element(By.ID, "id_description").send_keys(
            "Vanilla scented perfume for all genders")
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'submit\'])[3]").click()
        time.sleep(5)

    def test_edit_product(self):
        self.test_admin_login()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("new product")
        self.driver.find_element(
            By.CSS_SELECTOR, "#search-container-lg .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Edit").click()
        self.driver.find_element(By.ID, "id_name").click()
        self.driver.find_element(
            By.ID, "id_name").send_keys("the white bottle")
        element = self.driver.find_element(By.ID, "id_description")
        self.driver.execute_script("arguments[0].scrollIntoView();", element)
        self.driver.find_element(By.ID, "id_sku").click()
        self.driver.find_element(By.ID, "id_sku").send_keys("ER123456")
        target = self.driver.find_element_by_id('id_description')
        target.location_once_scrolled_into_view
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_description").click()
        self.driver.find_element(By.ID, "id_description").send_keys(
            ("Vanilla scented perfume for all genders. "
             "This perfume is the ultimate fragrance"))
        self.driver.find_element(
            By.XPATH, "//button[contains(.,\'Change Product\')]").click()
        time.sleep(5)

    def test_delete_product(self):
        self.test_admin_login()
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("the white bottle")
        self.driver.find_element(
            By.CSS_SELECTOR, "#search-container-lg .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Delete").click()
        time.sleep(5)

    def test_admin_logout(self):
        self.test_admin_login()
        # self.driver.get("https://eau-royal.herokuapp.com/")
        self.driver.get("http://192.168.1.18:8000/")
        self.driver.set_window_size(1920, 1080)
        self.driver.find_element(By.ID, "user-account-button").click()
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        self.driver.find_element(
            By.XPATH, "//button[contains(.,\'Sign Out\')]").click()
        time.sleep(5)
