# Generated by Django 3.2 on 2022-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, null=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
