# Generated by Django 3.2 on 2022-04-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220405_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='db_name',
            field=models.CharField(max_length=2),
        ),
    ]
